before:
  hooks:
    - go mod tidy
    - go generate ./...

release:
    disable: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    id: admincli
    binary: admincli

archives:
  - format: tar.gz
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - formats:
      - "deb"
    package_name: admincli
    section: misc
    maintainer: "André Baldeweg"
    description: "Offers tools for maintenance"
    contents:
      - src: admincli.yaml
        dst: /etc/admincli/admincli.yaml

checksum:
  name_template: "checksums.txt"
