version: 2.1

jobs:
    test-admincli:
        docker:
        - image: cimg/go:1.20.6
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: cd ./admincli && go mod tidy
        - run:
            name: Run the tests
            command: cd ./admincli && go test ./...
    test-conf:
        docker:
        - image: cimg/go:1.20.6
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: cd ./conf && go mod tidy
        - run:
            name: Run the tests
            command: cd ./conf && go test ./...
    test-conf-api:
        docker:
        - image: cimg/go:1.20.6
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: cd ./conf-api && go mod tidy
        - run:
            name: Run the tests
            command: cd ./conf-api && go test ./...
    test-search-api:
        docker:
        - image: cimg/go:1.20.6
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: cd ./search-api && go mod tidy
        - run:
            name: Run the tests
            command: cd ./search-api && go test ./...
    test-security:
        docker:
        - image: cimg/go:1.20.6
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: cd ./security && go mod tidy
        - run:
            name: Run the tests
            command: cd ./security && go test ./...

workflows:
  test:
    jobs:
      - test-admincli
      - test-conf
      - test-conf-api
      - test-search-api
      - test-security
