version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run: go version
      - run:  
          name: tidy
          command: cd ./conf && go mod tidy
      - run:
          name: test
          command: cd ./conf && go test ./...

workflows:
  test:
    jobs:
      - test