version: 2.1

orbs:
  go-module: timakin/go-module@volatile

executors:
  golang:
    docker:
      - image: 'circleci/golang:1.11.1-stretch'

workflows:
  build:
    jobs:
      - go-module/download:
          attach-workspace: true
          checkout: true
          executor: golang
          persist-to-workspace: true
          project_name: monorepo-go
          vendoring: false
          working-directory: conf
          workspace-root: github.com/incwadi-warehouse/monorepo-go