#!/bin/bash

PATH="$(yarn global bin):$PATH"

alias ll='ls -alF'

alias push='git push origin --follow-tags'

function tag()
{
  if [[ $(git status -s) ]];
    then
      echo "Git repo has uncommitted changes."
      git status -s;
    else
      git tag -a "v${1}" -m "v${1}";
  fi
}

function dev ()
{
  if [ -f go.sum ]
    then
      go run ./
  fi
}

function build ()
{
  if [ -f .goreleaser.yaml ]
    then
      goreleaser build --rm-dist
  fi
}
