version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: couchdb:latest
    restart: unless-stopped
    volumes:
      - couchdb-data:/opt/couchdb/data

volumes:
  couchdb-data:
