openapi: 3.0.0
info:
  title: Blog API
  version: v1
  description: Save and load content from the file system.

externalDocs:
    description: Github
    url: https://github.com/incwadi-warehouse/monorepo-go

servers:
    - url: http://localhost:8080/

paths:
  /article/{path}:
    get:
      summary: Get content by path
      description: Retrieves content from the filesystem based on the provided path.
      parameters:
        - in: path
          name: path
          schema:
            type: string
          required: true
          description: The path to the content file.
          example: test/test.md
      responses:
        '200':
          description: Content retrieved successfully.
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security:
        - APIKeyAuth: []

components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
