openapi: 3.0.0

info:
    version: 1.0.0
    title: search-api API
    description: Middleware for Search Index

externalDocs:
    description: Github
    url: https://github.com/incwadi-warehouse/monorepo-go

servers:
    - url: http://localhost:8080/api

tags:
    - name: index
      description: Index
    - name: mock
      description: Mockups - only for testing!

paths:
    /indexes/{index}/search:
        get:
            description: Search
            tags:
                - index
            parameters:
                - name: index
                  in: path
                  required: true
                  description: Index name
                  example: products
                  schema:
                    type: string
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/IndexResponse"
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Response"
                "401":
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Response"

    /indexes/{index}/rebuild:
        post:
            description: Create a new document
            tags:
                - index
            parameters:
                - name: index
                  in: path
                  required: true
                  description: Index name
                  example: products
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/IndexRequest"
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/IndexResponse"
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Response"
                "401":
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Response"
    /me:
        get:
            description: Mocks the auth API
            tags:
                - mock
            responses:
                "200":
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserResponse"
                "401":
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Response"

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            description: Enter your token e.g. "token"

    schemas:
        IndexResponse:
            type: object

        IndexRequest:
            type: object

        UserResponse:
            type: object
            required:
                - id
                - username
                - branch
            properties:
                id:
                    type: integer
                username:
                    type: string
                branch:
                    type: object
                    required:
                      - id
                    properties:
                      id:
                        type: integer

        Response:
            type: object
            required:
                - status
                - message
            properties:
                status:
                    type: integer
                message:
                    type: string

security:
    - bearerAuth: []
