name: Unit-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-admincli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run admincli tests
        working-directory: ./admincli
        run: |
          go mod tidy
          go test ./...

  test-conf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run conf tests
        working-directory: ./conf
        run: |
          go mod tidy
          go test ./...

  test-conf-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run conf-api tests
        working-directory: ./conf-api
        run: |
          go mod tidy
          go test ./...
